# This is ConfigMap. This holds your configuration data like settings, config files or env values.
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
# This is required field in ConfigMap. Each key becomes a filename when this ConfigMap is mounted
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: realworld-java21
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['app-service:8080']