version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: pg_local_app
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: "UTC"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build:
      context: ./app/realworld-java21-springboot3
    ports:
      - "8080:8080"
    env_file:
      - .env

volumes:
  pgdata: