apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  # Selector accesses to pods, You add metadata.labels.name to Deployment object
  selector:
    app: grafana
  ports:
  - name: grafana-port
    protocol: TCP
    # This port is exposed
    port: 3000
    # This is targeted pods port through ports.name
    targetPort: http-grafana