# This should be separated manifest and in gitignore. Well I have my secrets in .env file and spring through application.yaml
# gets those environment variables but deploying in kubernetes it wont get them so I have to use Secret object and ConfigMap object
# and tell app Deployment object that it can get them from here
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  DB_USERNAME: "postgres"
  DB_PASSWORD: "mysecretpassword"